Instancing benchmark demo
scenerygraphics/sciview pull request #586
Opened 2024-04-21 17:41 UTC by smlpt

This PR adds a benchmark to the `Demo > Advanced` menu.
It allows you to compare the conventional means of node publishing with instanced geometry, using spheres as objects.
The benchmark type can be run in four ways:
- publish each node separately
- publish all nodes cumulatively at the end
- populate the scene with instanced geometry sequentially
- populate the scene with instanced geometry using a parallel stream over the array, which is even faster

There are also parameters for the number of (instanced) particles (defaults to `1000`) and the spread in each dimension.

2024-04-22 01:32 UTC, kephale commented
One concern I have is that if a user doesn't know what to expect when running this, they could have a pretty bad time (e.g. if they run the `addNode publish all` with too many agents then it will get stuck).

Maybe some kind of warning in the `Command` dialog itself that they should be cautious, it could freeze their application, etc..

2024-04-22 09:39 UTC, smlpt commented
That's a good point.
I added a label with approximate timings:

![image](https://github.com/scenerygraphics/sciview/assets/83579186/aa198b09-5637-42c4-b654-d0750fe9405e)

2024-04-22 11:57 UTC, kephale commented
The last requests would be:
- mentioning this benchmark in the docs like @ctrueden suggested
- add a Gradle usage example in the docs

2024-04-23 09:15 UTC, smlpt commented
Added a benchmarking page to [the docs](https://docs.scenery.graphics/sciview) and registered a gradle task to run the benchmark from a CLI.

2024-04-23 13:38 UTC, skalarproduktraum requested changes
Just some minor things, otherwise great contribution! Thanks @smlpt 👍

2024-04-23 13:38 UTC, skalarproduktraum commented on src/main/kotlin/sc/iview/commands/demo/advanced/InstancingBenchmark.kt
> +            "publishAll" -> {runAddNodePublishAll()}
IIRC, no curly braces needed for single-function calls

2024-04-23 13:38 UTC, skalarproduktraum commented on src/main/kotlin/sc/iview/commands/demo/advanced/InstancingBenchmark.kt
> +        // This creates a sphere with 5cm radius and 10cm height as our parent.
This comment could be in the javadoc

2024-04-23 13:38 UTC, skalarproduktraum commented on src/main/kotlin/sc/iview/commands/demo/advanced/InstancingBenchmark.kt
> +        val startTime = System.currentTimeMillis()
Kotlin has helper functions for measuring timing, see https://kotlinlang.org/docs/time-measurement.html#measure-time 

In addition, when not using Kotlin's helpers, use System.nanoTime(), which uses the system's high-resolution timer (for more details see e.g. [this thread](https://stackoverflow.com/questions/351565/system-currenttimemillis-vs-system-nanotime) on StackOverflow)

2024-04-23 13:38 UTC, skalarproduktraum commented on src/main/kotlin/sc/iview/commands/demo/advanced/InstancingBenchmark.kt
> +    override fun run() {
Run could use some Javadoc on what it's doing

2024-04-23 15:16 UTC, smlpt commented
@skalarproduktraum done 👍

2024-04-30 08:57 UTC, skalarproduktraum approved these changes
Thanks, @smlpt 👍

2024-04-30 08:57 UTC, merged